name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐛 Bug Fixes'
    label: 'bug'
  - title: '🧰 Maintenance'
    label: 'maintenance'
  - title : '⚡ Performance'
    label: 'performance'
  - title: '✅ Tests'
    label: 'tests'
  - title: '📚 Documentation'
    label: 'documentation'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
no-changes-template: '- No changes'
template: |
  ## Changes

  $CHANGES
