name: "Debug: Print full PR JSON"

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, edited]

permissions:
  contents: read
  pull-requests: read

jobs:
  print-pr-debug:
    runs-on: ubuntu-latest

    steps:
      - name: Get and print full PR object
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            console.log(`🔍 PR #${prNumber} Vollständiges JSON:`);
            console.log(JSON.stringify(pr, null, 2));
